### ISSUE TITLE
Lab Report 1 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [idmkris/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- Well done putting the relevent links for VScode and OpenSSH. 
- [] All relevant code examples written with backticks (```)
- You should put all code examples or commands in backticks like this: 
- ```-scp /Users/joe/.ssh/id_rsa.pub cs15lwi22@ieng6.ucsd.edu:~/.ssh/authorized_keys```
- ```cd <dir>```
- ```ls -l <dir> ```
- etc...  You should add more detail and examples of each command that you tried here. 
- [] All screenshots correspond to the described steps
- Your screenshots are not rendering on the markdown page.  Check your syntax and make sure your images are displayed please.
- [] All titles of sections are formatted as headers or similar
- You should make each section a header so that each section is clearly separated. 
- [x] Lab report is on its own page, not the index page
- [] Last example counts keystrokes and shows how to run remotely saving time
- You should give more detail and describe in words what commands you are using in the image. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Overall good start, please make sure you images are displayed, commands are in backticks and you give plenty of detail for each section.  Also please make each section a header. 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by idmkris** [comment]
I am pretty sure my images are all shown on the web page. Do you mind explaining what "not rendering on the markdown page" is? Thanks

**Comment by mrkylesmith** [comment]
I see the images on the webpage now.  I see you added backticks to your code examples and added more explaination to the optimization part of the lab report.  The one suggestion I would make is maybe add more color contrast to your report, because it is still a slightly hard to discern code examples and it will help with readability.  Well done though, I have updated your lab report score.
